-- 코드를 입력하세요
SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE 1=1
AND IFNULL(OUTS.ANIMAL_ID,'') = ''
ORDER BY INS.DATETIME ASC
LIMIT 3